Repository Nircek/pikna-mapa, pull requests merged in 2019-11, with the labels that each got.

#23 Dodanie popupa w pinezce PIKa
  data.txt
Labels: [D]

#18 README (#1)
  README.md
Labels: [B]

#24 yyy... żeby działało na edge?
  index.html
  mystyle.css
Labels: [H]
